# Generated by Django 6.0.3 on 2026-04-21 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=10, null=True)),
                ('last_total_marks', models.FloatField(default=0.0, editable=False)),
                ('last_mean_score', models.FloatField(default=0.0, editable=False)),
                ('address', models.TextField(blank=True, help_text='Residential address', null=True)),
                ('has_leadership', models.BooleanField(default=False)),
                ('medical_condition', models.TextField(blank=True, help_text='Any underlying medical conditions', null=True)),
                ('current_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.classroom')),
                ('parents', models.ForeignKey(blank=True, limit_choices_to={'role': 'PARENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_record_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Excused', 'Excused'), ('Late', 'Late')], default='Present', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.students')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
