# Generated by Django 6.0.3 on 2026-05-13 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_school_user_school'),
        ('students', '0002_students_current_grade_students_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='students',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.school'),
        ),
    ]
