services:
  - type: web
    name: school-management-system
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn school_management_system.wsgi:application
