# Generated by Django 6.0.3 on 2026-04-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payement',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
