# Generated by Django 6.0.3 on 2026-04-22 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_payement_invoice_delete_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payement',
            options={'ordering': ['-date_paid']},
        ),
        migrations.RemoveField(
            model_name='payement',
            name='total_payable',
        ),
        migrations.AddField(
            model_name='payement',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payement',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payement',
            name='year',
            field=models.IntegerField(blank=True, default=2026, null=True),
        ),
        migrations.AlterField(
            model_name='payement',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='FeeStructure',
        ),
    ]
