# Generated by Django 6.0.3 on 2026-04-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_payement_options_remove_payement_total_payable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='reference',
            field=models.CharField(max_length=100),
        ),
    ]
