# Generated by Django 6.0.3 on 2026-05-13 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_school_user_school'),
        ('finance', '0004_alter_payement_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payement',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.school'),
        ),
    ]
