# Generated by Django 6.0.3 on 2026-07-03 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_exam_max_marks_exam_school_delete_schedule'),
        ('accounts', '0007_user_admission_number_user_id_number_and_more'),
        ('finance', '0005_payement_school'),
        ('students', '0004_parentstudentlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('M-PESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('TERMLY', 'Termly (3 months)'), ('ANNUALLY', 'Annually (9 months)')], default='MONTHLY', max_length=20)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, help_text='The fee amount from the fee structure', max_digits=10, null=True)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_payments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_manual_payments', to='accounts.school')),
                ('school_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payments', to='students.students')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('TERMLY', 'Termly (3 months)'), ('ANNUALLY', 'Annually (9 months)')], default='MONTHLY', max_length=20)),
                ('term', models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3')], default='TERM_1', max_length=20)),
                ('year', models.IntegerField(default=2026)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fee amount per student', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='e.g., Tuition fees for Term 1 2024')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academic.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='accounts.school')),
            ],
            options={
                'unique_together': {('school', 'class_assigned', 'billing_cycle', 'term', 'year')},
            },
        ),
    ]
