# Generated by Django 6.0.3 on 2026-07-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_schoolmpesaconfig_schoolsubscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsubscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active - Paid'), ('PENDING', 'Pending Payment'), ('OVERDUE', 'Overdue'), ('FREE', 'Free access'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
