# Generated by Django 6.0.3 on 2026-07-03 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_exam_max_marks_exam_school_delete_schedule'),
        ('accounts', '0007_user_admission_number_user_id_number_and_more'),
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('EXAM', 'Examination'), ('HOLIDAY', 'Holiday'), ('HALF_TERM', 'Half Term Break'), ('MEETING', 'Staff Meeting'), ('PARENT_MEETING', 'Parent Meeting'), ('SPORTS', 'Sports Event'), ('GRADUATION', 'Graduation'), ('OPEN_DAY', 'Open Day'), ('CLOSING', 'School Closing'), ('OPENING', 'School Opening'), ('WORKSHOP', 'Workshop/Training'), ('FIELD_TRIP', 'Field Trip'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(default='#2563eb', help_text='Hex color code', max_length=7)),
                ('notify_before', models.IntegerField(default=1, help_text='Days before to send notification')),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ALL', 'All Users'), ('CLASS', 'Specific Class'), ('STUDENT', 'Specific Student'), ('TEACHER', 'Specific Teacher'), ('PARENT', 'Specific Parent'), ('FEE', 'Fee Reminder'), ('RESULT', 'Result Published'), ('PAYMENT_SUBMITTED', 'Payment Submitted'), ('PAYMENT_APPROVED', 'Payment Approved'), ('PAYMENT_REJECTED', 'Payment Rejected'), ('FEE_BALANCE_UPDATE', 'Fee Balance Update'), ('FEES_CLEARED', 'Fees Cleared'), ('RECEIPT_READY', 'Receipt Ready'), ('ACCOUNT_CREATED', 'Account Created'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('PASSWORD_RESET', 'Password Reset'), ('PASSWORD_CHANGED', 'Password Changed'), ('STUDENT_REGISTERED', 'Student Registered'), ('PARENT_REGISTERED', 'Parent Registered'), ('TEACHER_REGISTERED', 'Teacher Registered'), ('BULK_UPLOAD_COMPLETE', 'Bulk Upload Complete'), ('BULK_UPLOAD_FAILED', 'Bulk Upload Failed'), ('RESULTS_SUBMITTED', 'Results Submitted'), ('RESULTS_APPROVED', 'Results Approved'), ('RESULTS_REJECTED', 'Results Rejected'), ('RESULTS_PUBLISHED', 'Results Published'), ('EXAM_CREATED', 'Exam Created'), ('CLASS_ASSIGNED', 'Class Assigned'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring'), ('SUBSCRIPTION_ACTIVATED', 'Subscription Activated'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired'), ('SYSTEM_UPDATE', 'System Update'), ('MAINTENANCE', 'Maintenance'), ('GENERAL', 'General')], default='ALL', max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_dd6756_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_18c9bd_idx'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminder',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='academic.exam'),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='target_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='academic.classroom'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='notification.schoolevent'),
        ),
        migrations.AlterUniqueTogether(
            name='reminder',
            unique_together={('event', 'recipient')},
        ),
    ]
