# Generated by Django 6.0.3 on 2026-05-25 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_schoolsubscription_subscriptioninvoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMpesaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(blank=True, help_text='Paybill/Till Number', max_length=50, null=True)),
                ('consumer_key', models.CharField(blank=True, max_length=200, null=True)),
                ('consumer_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('passkey', models.CharField(blank=True, max_length=200, null=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox (Testing)'), ('production', 'Production (Live)')], default='sandbox', max_length=20)),
                ('is_configured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('test_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_config', to='accounts.school')),
            ],
        ),
        migrations.DeleteModel(
            name='SubscriptionPayment',
        ),
    ]
