# Generated by Django 6.0.3 on 2026-05-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_subscriptionpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'super_Admin'), ('ADMIN', 'admin'), ('HEAD_TEACHER', 'Head Teacher'), ('TEACHER', 'teacher'), ('STUDENT', 'student'), ('PARENT', 'parent')], default='STUDENT', max_length=20),
        ),
    ]
