# Generated by Django 6.0.3 on 2026-07-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_admission_number_user_id_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolsubscription',
            name='school',
        ),
        migrations.RemoveField(
            model_name='subscriptioninvoice',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='subscriptioninvoice',
            name='school',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='school',
        ),
        migrations.DeleteModel(
            name='SchoolMpesaConfig',
        ),
        migrations.DeleteModel(
            name='SchoolSubscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionInvoice',
        ),
        migrations.DeleteModel(
            name='SubscriptionPayment',
        ),
    ]
