# Generated by Django 6.0.3 on 2026-07-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_schoolsubscription_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSetupProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_1_completed', models.BooleanField(default=False)),
                ('step_2_completed', models.BooleanField(default=False)),
                ('step_3_completed', models.BooleanField(default=False)),
                ('step_4_completed', models.BooleanField(default=False)),
                ('step_5_completed', models.BooleanField(default=False)),
                ('school_profile', models.JSONField(blank=True, default=dict)),
                ('selected_subjects', models.JSONField(blank=True, default=list)),
                ('head_teacher_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_progress', to='accounts.school')),
            ],
            options={
                'verbose_name': 'School Setup Progress',
                'verbose_name_plural': 'School Setup Progresses',
            },
        ),
    ]
