# Generated by Django 6.0.3 on 2026-07-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_schoolsetupprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolSetupProgress',
        ),
    ]
