# Generated by Django 6.0.3 on 2026-07-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_schoolsetupprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
