# Generated by Django 6.0.3 on 2026-07-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_admin_id_user_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'super_Admin'), ('ADMIN', 'admin'), ('HEAD_TEACHER', 'Head Teacher'), ('BURSAR', 'Bursar'), ('SECRETARY', 'Secretary'), ('TEACHER', 'teacher'), ('STUDENT', 'student'), ('PARENT', 'parent')], default='STUDENT', max_length=20),
        ),
    ]
