# Generated by Django 6.0.3 on 2026-04-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_teacher_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectAllocation',
        ),
    ]
