# Generated by Django 6.0.3 on 2026-04-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_delete_subjectallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='capacity',
        ),
    ]
