# Generated by Django 6.0.3 on 2026-05-04 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_results_approved_at_results_approved_by_and_more'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_number', models.IntegerField(unique=True)),
                ('grade_name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('PRIMARY', 'Primary School'), ('JUNIOR', 'Junior School'), ('SENIOR', 'Senior School')], default='PRIMARY', max_length=20)),
                ('is_graduation_grade', models.BooleanField(default=False)),
                ('next_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.gradelevel')),
            ],
            options={
                'ordering': ['grade_number'],
            },
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('from_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_from', to='academic.gradelevel')),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_history', to='students.students')),
                ('to_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_to', to='academic.gradelevel')),
            ],
            options={
                'ordering': ['-promoted_at'],
            },
        ),
    ]
