# Generated by Django 6.0.3 on 2026-05-13 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_gradelevel_promotionhistory'),
        ('accounts', '0002_school_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='promotionhistory',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_histories', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='results',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('OPENER', 'Opener Exam'), ('MIDTERM', 'Midterm Exam'), ('ENDTERM', 'End of Term')], max_length=20),
        ),
    ]
