# Generated by Django 6.0.3 on 2026-05-13 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_classroom_school_promotionhistory_school_and_more'),
        ('accounts', '0002_school_user_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='academic.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='accounts.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academic.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='academic.teacher')),
            ],
            options={
                'ordering': ['classroom__name', 'subject__name'],
                'unique_together': {('school', 'classroom', 'subject')},
            },
        ),
    ]
