# Generated by Django 6.0.3 on 2026-05-18 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_subjectallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='fee_amount',
        ),
    ]
