# Generated by Django 6.0.3 on 2026-05-29 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_remove_classroom_fee_amount'),
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='max_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='accounts.school'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
